### ISSUE TITLE
Please add an option for translation like this

### ISSUE THREAD

**Issue by rsoorajs** [PasaOpasen/TranslatorBot#4]
if i am an group admin and i wanna translate someones chat ..what should i do ? copy pasting is boaring..if we should to replay that message something like /translate or /tr or .tr that must be translate..hows it ?

also ## at the is not translating..only ##+ is translating

**Comment by rsoorajs** [comment]
also auto translation is not working in groups or bot

**Comment by PasaOpasen** [comment]
@telegrambotdev now it's true because of free deploy and block my IP. The reason is too frequent usage of translation API that means my IP (where app deployed) should be blocked

Okay, soon I will increase time pause for ## translation and redeploy; it will work 'slower' but more stable
