### ISSUE TITLE
Move to pygoogletranslation instead of googletrans

### ISSUE THREAD

**Issue by rsoorajs** [PasaOpasen/TranslatorBot#5]
Googletrans is no longer free,so i should suggest to use a free and unlimited google translator api

`pip install pygoogletranslation`

you can check this here

https://github.com/Saravananslb/py-googletranslation

**Comment by PasaOpasen** [comment]
@telegrambotdev Now I see that 'Googletrans is no longer free', it's true

So I will use this new package, but not today cuz it has some bags they must solved

**Comment by rsoorajs** [comment]
okay
